### ISSUE TITLE
Get selection range

### ISSUE THREAD

**Issue by santi-g-s** [kyle-n/HighlightedTextView#30] opened 2021-01-14 00:34 UTC
**Is your feature request related to a problem? Please describe.**
I want to be able to insert markdown attributes into the string programmatically. 

I.e. when text is selected, press 'bold' button -> inserts '**' on either end of selected range in string.

**Describe the solution you'd like**
Something like:
'''
onSelectionDidChange: (range) -> Void
'''

Or anything else that will provide the selected text range.

**Describe alternatives you've considered**
I've looked into Delegate methods for NSTextviews/ UITextViews where you can extract the selectedTextRange and just want a way to get this out of the HighlightedTextEditor.

**Comment by kyle-n** [comment] 2021-01-14 01:45
Thank you for the detailed request and looking into this. Since it is a duplicate of #24, I am closing this to continue the conversation over there.

**Closed as completed by kyle-n** 2021-01-14 01:45 UTC
Labels: duplicate, enhancement
